CREATE DATABASE  InLock_Games_Tarde;

USE InLock_Games_Tarde;

CREATE TABLE TipoUsuario (
	IdTipoUsuario		INT PRIMARY KEY IDENTITY,
	Titulo				VARCHAR (200) NOT NULL UNIQUE
);

CREATE TABLE Usuarios (
	IdUsuario			INT PRIMARY KEY IDENTITY,
	Email				VARCHAR(255) NOT NULL UNIQUE,
	Senha				VARCHAR(200) NOT NULL,
	IdTipoUsuario		INT FOREIGN KEY REFERENCES TipoUsuario (IdTipoUsuario)
);

CREATE TABLE Estudios (
	IdEstudio			INT PRIMARY KEY IDENTITY,
	NomeEstudio			VARCHAR(200) NOT NULL UNIQUE
);

CREATE TABLE Jogos (
	IdJogo				INT PRIMARY KEY IDENTITY,
	NomeJogo			VARCHAR(255) NOT NULL UNIQUE,
	Descricao			VARCHAR(255) NOT NULL,
	DataLancamento		DATETIME NOT NULL, 
	Valor				FLOAT,
	IdEstudio			INT FOREIGN KEY REFERENCES Estudios (IdEstudio)
);

SELECT * FROM TipoUsuario;
SELECT * FROM Usuarios;
SELECT * FROM Estudios;
SELECT * FROM Jogos;